disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Francesco M. Ruscio"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "IMG_4044.HEIC "

["params.author"]
name = "Francesco M. Ruscio"
image = "IMG_4044.jpg "
