disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Francesco M. Ruscio"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"

["params.author"]
name = "Francesco M. Ruscio"
image = "img/IMG_4044.jpg"
headline = "PhD @ AITHYRA | Founder @ Crumbles Street"
links = [
    { email = "mailto:francescoruscio.research@gmail.com" },
    { github = "https://github.com/francescoshox" },
    { linkedin = "linkedin.com/in/francesco-maria-ruscio-62b41a222" },
    { x-twitter = "https://x.com/francescoshox" }
  ]